---
services: docker

before_install:
  # Upgrade Docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

jobs:
  include:
    - stage: Build/Test/Push the docker image
      script:
      # Build the Dockerfile
      - docker build -t docker-debian9-ansible .

      # Test running the container
      - docker run --name test-container -d --privileged -v /var/run/docker.sock:/var/run/docker.sock docker-debian9-ansible

      # Verifies Docker is installed
      - docker exec --tty test-container env TERM=xterm docker --version

      # Verifies Python is installed
      - docker exec --tty test-container env TERM=xterm python --version

      # Verifies Ansible is installed
      - docker exec --tty test-container env TERM=xterm ansible --version

      # Verifies Molecule is installed
      - docker exec --tty test-container env TERM=xterm molecule --version

      # Verifies virtualenv is installed
      - docker exec --tty test-container env TERM=xterm virtualenv --version

      # Pushes the docker image to Docker Hub
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag docker-debian9-ansible $DOCKER_USERNAME/docker-debian9-ansible:latest
      - docker push $DOCKER_USERNAME/docker-debian9-ansible:latest